name: Deploy API to Hostinger

on:
  push:
    branches:
      - dev

jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4

# IBINALIK: Setup PHP (Kailangan ito para makapag-run ng Composer)
    - name: ğŸ˜ Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, pdo, pdo_mysql, mysqli

    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

   
    - name: ğŸ“¦ Install Composer Dependencies
      run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader


    - name: ğŸ“‚ Deploy System Files (Root)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        
       
        server-dir: ./public_html
        

        exclude: |
          **/vendor/**
          **/public/**
          **/node_modules/**
          **/.git*
          **/.git*/**
          **/tests/**
          **/storage/*.key
          .env
          .env.example
          .editorconfig
          .gitattributes
          .github/**
          .styleci.yml
          CHANGELOG.md
          composer.json
          composer.lock
          phpunit.xml
          README.md
          

    - name: ğŸ“‚ Deploy Public Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        
        local-dir: public/
        server-dir: public_html/